version: '3.1'
services:
   mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=testdb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p root || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
   product:
    image: microservice
    ports:
      - "9991:8080"
    environment:
      - DB_URL=jdbc:mysql://mysqldb:3306/testdb
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      mysqldb:
          condition: service_healthy
    restart: always